source "$THEME_DIR/catppuccin-macchiato.sh"

BAR_COLOR="$BASE"
BAR_BLUR_RADIUS=30

## Geometry
BAR_POSITION="top"
BAR_HEIGHT=40
BAR_PADDING=10
BAR_Y_OFFSET=10
BAR_CORNER_RADIUS=9
BAR_MARGIN=10

# Item Defaults
## Colors
BACKGROUND_COLOR="$TRANSPARENT"
BACKGROUND_BORDER_COLOR="$TRANSPARENT"
BACKGROUND_BORDER_WIDTH=0
LABEL_ALIGN="center"
LABEL_COLOR="$TEXT"
LABEL_HIGHLIGHT_COLOR="$TEXT"
ICON_COLOR="$TEXT"

## Fonts
ICON_BASE_FONT="JetBrainsMono Nerd Font"
ICON_FONT="$ICON_BASE_FONT:Bold:14.0"
LABEL_BASE_FONT="JetBrainsMono Nerd Font"
LABEL_FONT="$LABEL_BASE_FONT:Regular:14.0"
LABEL_HIGHLIGHT_FONT="$LABEL_BASE_FONT:ExtraBold:16.0"

## Geometry
BACKGROUND_CORNER_RADIUS=4
BACKGROUND_HEIGHT=28
LABEL_Y_OFFSET=1
LABEL_PADDING=4
BRACKET_BACKGROUND_BORDER_WIDTH=2
BRACKET_BACKGROUND_CORNER_RADIUS=6

### GENERAL
PADDINGS=3
