#!/usr/bin/env bash

source "$CONFIG_DIR/environment"
source "$THEME_DIR/current.sh"

# Configure general bar appearance.
bar_config=(
  blur_radius="$BAR_BLUR_RADIUS"
  border_color="$BAR_BORDER_COLOR"
  color="$BAR_COLOR"
  corner_radius="$BAR_CORNER_RADIUS"
  height="$BAR_HEIGHT"
  margin="$BAR_MARGIN"
  position="$BAR_POSITION"
  padding_left="$BAR_PADDING"
  padding_right="$BAR_PADDING"
  y_offset="$BAR_Y_OFFSET"
  shadow=on
  sticky=on
  topmost=off
)

icon_defaults=(
  icon.color="$ICON_COLOR"
  icon.font="$ICON_FONT"
  icon.padding_left="$PADDINGS"
  icon.padding_right="$PADDINGS"
)

label_defaults=(
  label.color="$TEXT"
  label.font="$LABEL_FONT"
  label.padding_left="$PADDINGS"
  label.padding_right="$PADDINGS"
  label.highlight_color="$LABEL_HIGHLIGHT_COLOR"
)

background_defaults=(
  background.color="$BACKGROUND_COLOR"
  background.corner_radius=9
  background.corner_radius="$BACKGROUND_CORNER_RADIUS"
  background.padding_left="$PADDINGS"
  background.padding_right="$PADDINGS"
  background.height="$BACKGROUND_HEIGHT"
)

popup_defaults=(
  popup.height=30
  popup.horizontal=false
  popup.background.border_color="$BLUE"
  popup.background.border_width=2
  popup.background.color="$MANTLE"
  popup.background.corner_radius=11
  popup.background.shadow.drawing=on
)

sketchybar --bar "${bar_config[@]}" \
  --default \
  updates=when_shown \
  "${icon_defaults[@]}" \
  "${label_defaults[@]}" \
  "${background_defaults[@]}" \
  "${popup_defaults[@]}"

source "$ITEM_DIR/left.sh"
source "$ITEM_DIR/right.sh"

# Automatically apply configuration changes
sketchybar --hotload on

# Force all scripts to run the first time (never do this in a script)
sketchybar --update

# Initialize focused workspace
sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$(aerospace list-workspaces --focused)
